# Generated by Django 2.2.10 on 2021-03-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True))
            ],
        ),
    ]
